version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"
    volumes:
      - "/var/lib/postgresql/data"

  exchangemachine:
    build: ./src
    command: /code/run.sh
    user: root
    volumes:
      - ./src:/code
    ports:
      - "12345:12345"
    depends_on:
      - db
